#!/bin/bash

#################################################
# Script to add wifi network config
#################################################

echo "This script will create a file that will update your PiRover's wireless config the next time it boots."
echo "Please plug your PiRover's memory card into your computer and make sure it is properly mounted."
echo ""

echo "Please enter your wireless network's SSID (name):"
read ssid
echo ""
ssid=${ssid//\"/} # Remove quotes

echo "Please enter your wireless network's psk (passphrase):"
read psk
echo ""
psk=${psk//\"/} # Remove quotes

DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
echo -e "network={\n\tssid=\"$ssid\"\n\tpsk=\"$psk\"\n}\n" >> "$DIR/wpa.conf"
echo "Wrote data to $DIR/wpa.conf"
echo "Next time your PiRover boots, it will attempt to connect to \"$ssid\""

read -p "Press enter to exit..."